// D: *types something on computer* Damn... I feel kind of lonely and depressed...
// P: This is bad... Can I help somehow?
// D: idk...
// P: By the way, my sister is coming today, maybe she can help you somehow?
// D: *Eyes shine* Maybe...